name       : haskell-regex-applicative
version    : 0.3.3.1
release    : 4
source     :
    - https://hackage.haskell.org/package/regex-applicative-0.3.3.1/regex-applicative-0.3.3.1.tar.gz : 8f064fc23b58fcdd0ef3ce9e2597d877a86bec1770f2b877cb3057b54bb70a5c
license    : BSD-3-Clause
component  : programming.haskell
summary    : regex-applicative is a Haskell library for parsing using regular expressions. Parsers can be built using Applicative interface.
description: |
    regex-applicative is a Haskell library for parsing using regular expressions. Parsers can be built using Applicative interface.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
