name       : haskell-regex-applicative
version    : 0.3.3
release    : 1
source     :
    - http://hackage.haskell.org/package/regex-applicative-0.3.3/regex-applicative-0.3.3.tar.gz : 6659a2cc1c8137d77ef57f75027723b075d473354d935233d98b1ae1b03c3be6
license    : BSD-3-Clause
component  : programming.haskell
summary    : regex-applicative is a Haskell library for parsing using regular expressions. Parsers can be built using Applicative interface. 
description: |
    regex-applicative is a Haskell library for parsing using regular expressions. Parsers can be built using Applicative interface. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
